name: CI/CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.actor }}/java-api:${{ github.sha }} .
          docker tag ghcr.io/${{ github.actor }}/java-api:${{ github.sha }} ghcr.io/${{ github.actor }}/java-api:latest

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.actor }}/java-api:${{ github.sha }}
          docker push ghcr.io/${{ github.actor }}/java-api:latest



